version: '3'
services:
 springboot:
  image: spring-phone-validation
  container_name: BE_phoneValidation
  ports:
   - "8080:8080"
  restart: always
 angular:
  image: angular-phone-validation
  container_name: FE_phoneValidation
  command: sh -c "cd /usr/local/app/ && ng serve --host 0.0.0.0 "
  ports:
   - "4200:4200"
  restart: always
  depends_on:
   - springboot

